- name: Download Kitty installation script
  get_url:
    url: https://sw.kovidgoyal.net/kitty/installer.sh
    dest: /tmp/install_kitty.sh

- name: Run Kitty installation script
  ansible.builtin.shell: sh /tmp/install_kitty.sh
  become_user: fjk

- name: "Clone eza release from repo"
  vars:
    eza_version: v0.19.0
  ansible.builtin.get_url:
    url: "https://github.com/eza-community/eza/releases/download/{{ eza_version }}/eza_x86_64-unknown-linux-gnu.tar.gz"
    dest: "/tmp/"
  tags: eza

- name: "Extract eza install files"
  become: true
  unarchive:
    src: "/tmp/eza_x86_64-unknown-linux-gnu.tar.gz"
    dest: "/opt/eza"
  tags: eza
