- name: "Clone nvm release from repo (node version manager)"
  vars:
    nvm_version: v0.40.0
    node_version: "20"
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_version }}/install.sh"
    dest: "/tmp/install_nvm.sh"
  tags: nvm

- name: Run nvm installation script
  ansible.builtin.shell: bash /tmp/install_nvm.sh 
  args:
    creates: /home/fjk/.nvm
  become_user: fjk
  
- name: Run nvm install node & npm
  ansible.builtin.shell: nvm install 20
