- name: "Clone xremaps release from repo for gnome wayland"
  vars:
    xremaps_version: v0.10.0
  ansible.builtin.get_url:
    url: "https://github.com/xremap/xremap/releases/download/{{ xremaps_version }}/xremap-linux-x86_64-gnome.zip"
    dest: "/tmp/"
  tags: eza

- name: "Extract xremaps install files"
  become: true
  unarchive:
    src: "xremap-linux-x86_64-gnome.zip"
    dest: "/opt/"
  tags: eza
