- name: "Clone neovim release from repo"
  vars:
    neovim_version: v0.10.1
  ansible.builtin.get_url:
    url: "https://github.com/neovim/neovim/releases/download/{{ neovim_version }}/nvim-linux64.tar.gz"
    dest: "/tmp/"
  tags: neovim

- name: "Extract Neovim install files"
  become: true
  unarchive:
    src: "/tmp/nvim-linux64.tar.gz"
    dest: "/opt/"
  tags: neovim
