---
- hosts: 127.0.0.1 
  connection: local
  become: true
  tasks:
    - name: "Install bat"
      apt:
        update_cache: yes
        name:
          - bat
        state: latest
    - name: "Install exa"
      apt:
        update_cache: yes
        name:
          - exa
        state: latest
    - name: "Install Starship"
      uri:
        url: 'https://starship.rs/install.sh'
        method: GET
        register: result
