---
- hosts: 127.0.0.1 
  connection: local
  tasks:
    - name: "Install bat"
      apt:
        update_cache: yes
        name:
          - bat
        state: latest
    - name: "Install exa"
      apt:
        update_cache: yes
        name:
          - exa
        state: latest
    - name: "Install cmake"
      apt:
        update_cache: yes
        name:
          - cmake
        state: latest
    - import_tasks: setup_zsh.yml
