- name: Retrieve the current user's name
  set_fact:
    current_user: "{{ lookup('env', 'USER') }}"

- name: Install curl (for starship installation)
  become: true
  ansible.builtin.package:
    state: latest
    name: curl

- name: Install Zsh
  become: true
  ansible.builtin.package:
    name: zsh
    state: latest

- name: Set Zsh as default shell
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/zsh

- name: "Add a line to /etc/zsh/zshenv"
  lineinfile:
    path: /etc/zsh/zshenv
    line: 'export ZDOTDIR="/home/{{ current_user }}/.config/zsh"'
    create: no
    state: present
    insertafter: EOF  # Ensure the line is added at the end of the file

- name: Verify Zsh installation
  ansible.builtin.shell: zsh --version
  changed_when: false

- name: Download Oh My Zsh installation script
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/install_ohmyzsh.sh

- name: Run Oh My Zsh installation script
  command: sh /tmp/install_ohmyzsh.sh --unattended

- name: Get starship install script
  ansible.builtin.get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship_install.sh
    mode: '0755'

- name: Install starship with installation script
  become: true
  ansible.builtin.shell:
    cmd: /tmp/starship_install.sh --yes
    executable: /bin/sh

- name: Assert starship is installed
  ansible.builtin.shell: starship --version
  changed_when: false
