- name: Set Git user name
  ansible.builtin.git_config:
    name: user.name
    value: "fjodorgit"
    scope: global

- name: Set Git user email
  ansible.builtin.git_config:
    name: user.email
    value: "f.kholodkov@gmail.com"
    scope: global

- name: Enable Git color UI
  ansible.builtin.git_config:
    name: color.ui
    value: auto
    scope: global
