---
- hosts: 127.0.0.1 
  connection: local
  become: true
  tasks:
    - name: "Install bat"
      apt:
        update_cache: yes
        name:
          - bat
        state: latest
    - name: "Install cmake"
      apt:
        update_cache: yes
        name:
          - cmake
        state: latest
    - import_tasks: setup_binaries.yml
    - import_tasks: setup_eza.yml
    - import_tasks: setup_kitty.yml
    - import_tasks: setup_neovim.yml
    - import_tasks: setup_zsh.yml
